// Code generated by go2go; DO NOT EDIT.


//line /Users/yuepan/go/src/github.com/smallnest/gofu/consumer.go2:1
package gofu

//line /Users/yuepan/go/src/github.com/smallnest/gofu/consumer.go2:1
import "testing"

//line /Users/yuepan/go/src/github.com/smallnest/gofu/consumer.go2:1
type Importable୦ int

//line /Users/yuepan/go/src/github.com/smallnest/gofu/consumer.go2:1
var _ = testing.AllocsPerRun
