// Code generated by go2go; DO NOT EDIT.


//line /Users/yuepan/go/src/github.com/smallnest/gofu/function_test.go2:1
package gofu

//line /Users/yuepan/go/src/github.com/smallnest/gofu/function_test.go2:1
import "testing"

//line /Users/yuepan/go/src/github.com/smallnest/gofu/function_test.go2:5
func TestFunction(t *testing.T) {

}

//line /Users/yuepan/go/src/github.com/smallnest/gofu/function_test.go2:7
var _ = testing.AllocsPerRun
