// Code generated by go2go; DO NOT EDIT.


//line /Users/yuepan/go/src/github.com/smallnest/gofu/ordered.go2:1
package gofu

//line /Users/yuepan/go/src/github.com/smallnest/gofu/ordered.go2:1
import "testing"

//line /Users/yuepan/go/src/github.com/smallnest/gofu/ordered.go2:4
type G interface{}

//line /Users/yuepan/go/src/github.com/smallnest/gofu/ordered.go2:4
var _ = testing.AllocsPerRun
